"""empty message

Revision ID: 708104c9059f
Revises: 8878f4aa11db
Create Date: 2026-05-04 07:47:20.263362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '708104c9059f'
down_revision: Union[str, None] = '8878f4aa11db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE productstatus ADD VALUE IF NOT EXISTS 'HARD_BLOCKED'")
    op.add_column('skus', sa.Column('cost_price', sa.Integer(), server_default='0', nullable=False))
    op.add_column('skus', sa.Column('discount', sa.Integer(), server_default='0', nullable=False))
    op.add_column('skus', sa.Column('image', sa.String(length=255), server_default='', nullable=False))
    op.add_column('skus', sa.Column('reserved_quantity', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('skus', 'images')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skus', sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('skus', 'reserved_quantity')
    op.drop_column('skus', 'image')
    op.drop_column('skus', 'discount')
    op.drop_column('skus', 'cost_price')
    # ### end Alembic commands ###
