"""Add warehouse operators and invoice accepted_by

Revision ID: 2baf98d6a7e5
Revises: 27ddfb2984ec
Create Date: 2026-05-18 08:00:28.070454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2baf98d6a7e5'
down_revision: Union[str, None] = '27ddfb2984ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_operators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_operators_email'), 'warehouse_operators', ['email'], unique=True)
    op.add_column('invoices', sa.Column('accepted_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'warehouse_operators', ['accepted_by'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'accepted_by')
    op.drop_index(op.f('ix_warehouse_operators_email'), table_name='warehouse_operators')
    op.drop_table('warehouse_operators')
    # ### end Alembic commands ###
