"""Initial migration

Revision ID: 6c453f95188b
Revises: 
Create Date: 2026-04-03 07:47:31.128763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c453f95188b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create ProductStatus enum type
    product_status = sa.Enum('CREATED', 'ON_MODERATION', 'MODERATED', 'BLOCKED', 'HARD_BLOCKED', name='productstatus')
    
    op.create_table('categories',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('path', sa.String(), nullable=True),
        sa.Column('level', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_index(op.f('ix_categories_path'), 'categories', ['path'], unique=False)

    op.create_table('products',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status', product_status, nullable=False),
        sa.Column('images', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('characteristics', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('category_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_title'), 'products', ['title'], unique=False)

    op.create_table('skus',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('price', sa.Integer(), nullable=False),
        sa.Column('active_quantity', sa.Integer(), nullable=False),
        sa.Column('images', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('characteristics', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('product_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skus_name'), 'skus', ['name'], unique=False)

    # Now add the is_active column as originally intended
    op.add_column('categories', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skus')
    op.drop_table('products')
    op.drop_table('categories')
    sa.Enum(name='productstatus').drop(op.get_bind())
    # ### end Alembic commands ###
