"""add_reserve_operations

Revision ID: 95dd223263d9
Revises: 2baf98d6a7e5
Create Date: 2026-05-20 07:37:39.805971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95dd223263d9'
down_revision: Union[str, None] = '2baf98d6a7e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserve_operations',
    sa.Column('idempotency_key', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_reserve_operations_order_id'), 'reserve_operations', ['order_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reserve_operations_order_id'), table_name='reserve_operations')
    op.drop_table('reserve_operations')
    # ### end Alembic commands ###
