"""SKU model update

Revision ID: fa4e607750a9
Revises: 6bfce5725490
Create Date: 2026-05-16 15:24:54.382128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa4e607750a9'
down_revision: Union[str, None] = '6bfce5725490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skus', sa.Column('cost_price', sa.Integer(), server_default='0', nullable=False))
    op.add_column('skus', sa.Column('discount', sa.Integer(), server_default='0', nullable=False))
    op.add_column('skus', sa.Column('active_quantity', sa.Integer(), server_default='0', nullable=False))
    op.add_column('skus', sa.Column('reserved_quantity', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skus', 'reserved_quantity')
    op.drop_column('skus', 'active_quantity')
    op.drop_column('skus', 'discount')
    op.drop_column('skus', 'cost_price')
    # ### end Alembic commands ###
