"""Add blocking fields

Revision ID: 7c7d49d92615
Revises: fa4e607750a9
Create Date: 2026-05-17 09:42:16.518093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c7d49d92615'
down_revision: Union[str, None] = 'fa4e607750a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('blocking_reason_title', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('field_reports', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'field_reports')
    op.drop_column('products', 'blocking_reason_title')
    # ### end Alembic commands ###
