"""Implementation brought into line with API spec

Revision ID: 6f069c523eae
Revises: 8878f4aa11db
Create Date: 2026-05-12 06:18:41.927378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f069c523eae'
down_revision: Union[str, None] = '8878f4aa11db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skus', sa.Column('stock_quantity', sa.Integer(), nullable=False))
    op.add_column('skus', sa.Column('article', sa.String(length=100), nullable=True))
    op.drop_column('skus', 'active_quantity')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skus', sa.Column('active_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('skus', 'article')
    op.drop_column('skus', 'stock_quantity')
    # ### end Alembic commands ###
