"""Product model update

Revision ID: 6bfce5725490
Revises: 6f069c523eae
Create Date: 2026-05-16 13:22:48.106014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bfce5725490'
down_revision: Union[str, None] = '6f069c523eae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('slug', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('blocking_reason_id', sa.UUID(), nullable=True))
    op.add_column('products', sa.Column('moderator_comment', sa.Text(), nullable=True))
    op.drop_column('products', 'blocked')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('blocked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('products', 'moderator_comment')
    op.drop_column('products', 'blocking_reason_id')
    op.drop_column('products', 'slug')
    # ### end Alembic commands ###
